steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: bash
  args:
    - ./scripts/update_version
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=github-token-access --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
# TODO: (mtauseeq) use build variable to replace name and email, Also use build variables to replace new branch name
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    echo "Set the git config..."
    git config user.name Tuseeq1
    git config user.email mtauseeq@google.com
    git remote set-url origin https://Tuseeq1:$(cat token.txt)@github.com/dataform-co/dataform.git
    export git_branch_name=npm_veriosn_$(cat version.bzl | grep DF_VERSION | awk '{ print $3 }' | sed "s/\"//g")
    echo "Create new branch $git_branch_name..."
    git checkout -b $git_branch_name
    git add version.bzl
    git commit -m "Update the npm package version"
    echo "Push changes to remote"
    git push origin $git_branch_name
    echo $git_branch_name > git_branch_name.txt
- name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    echo "Create PR..."
    gh auth login --with-token < token.txt
    gh pr create -t "Publish a new NPM versions" -b "Updating NPM package version to $(cat git_branch_name.txt)" -B master -H $(cat git_branch_name.txt)
# - name: 'gcr.io/$PROJECT_ID/github'
#   args: [ 'pr', 'create', '-t', '"Publish a new NPM versions"', '-b', '"Pull request body"', '-B', 'npm-package-automation', '-H', '$(cat git_branch_name.txt)', '-r', 'Tuseeq1']