steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    secretEnv: ['NPM_TOKEN']
  - name: gcr.io/cloud-builders/bazel:5.4.0
    entrypoint: bash
    args:
      - ./scripts/publish
  - name: gcr.io/cloud-builders/gcloud:latest
    entrypoint: "ls"
    args: ["-lah","/workspace"]
availableSecrets:
  secretManager:
  - versionName: projects/178487900909/secrets/npm-publish-token/versions/1
    env: 'NPM_TOKEN'
artifacts:
  npmPackages:
  - repository: 'https://us-central1-npm.pkg.dev/dataform-open-source/dataform-open-source'
    packagePath: './bazel-bin/packages/@dataform/cli'
options:
  machineType: E2_HIGHCPU_8
  requestedVerifyOption: VERIFIED
timeout: 3600s
