steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: bash
  args:
    - ./scripts/update_version
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=github-token-access --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    gh auth login --with-token < token.txt
    gh auth status
# TODO: (mtauseeq) use build variable to replace name and email
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    echo $(https://Tuseeq1:$(cat token.txt)@github.com/dataform-co/dataform.git)
    git checkout -b npm_version_update
    git config user.name Tuseeq1
    git config user.email mtauseeq@google.com
    git remote set-url origin https://Tuseeq1:$(cat token.txt)@github.com/dataform-co/dataform.git
    git config list
    git add version.bzl
    git commit -m "Update the npm package version"
    git push origin npm_version_update
    git status 
# - name: 'gcr.io/cloud-builders/git'
#   args: ['status']
# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: 'bash'
#   args: [ '-c', "gcloud secrets versions access latest --secret=github-token-access --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
# - name: 'gcr.io/$PROJECT_ID/github'
#   args: ['repo', 'view', 'dataform-co/dataform']