steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', '-b', 'npm_version_update']
- name: 'gcr.io/cloud-builders/git'
  args: ['status']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: bash
  args:
    - ./scripts/update_version
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=github-token-access --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: 'gcr.io/$PROJECT_ID/github'
  args: ['auth', 'status']
# TODO: (mtauseeq) use build variable to replace name and email
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config --global user.name Tuseeq1
    git config --global user.email mtauseeq@google.com
    git config list
    git add version.bzl
    git commit -m "Update the npm package version"
    git status
# - name: 'gcr.io/cloud-builders/git'
#   args: ['status']
# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: 'bash'
#   args: [ '-c', "gcloud secrets versions access latest --secret=github-token-access --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
# - name: 'gcr.io/$PROJECT_ID/github'
#   args: ['repo', 'view', 'dataform-co/dataform']