steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      tail ~.npmrc
    secretEnv: ['NPM_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/178487900909/secrets/npm-publish-token/versions/1
    env: 'NPM_TOKEN'
timeout: 3600s
