steps:
# We have github personal access token stored in `github-token-access` secret in our GCP project.
# This step downloads it and store it in token.txt file for later steps to use for authentication.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=github-token-access --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt" ]
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    _GITHUB_USER=$_GITHUB_USER _GITHUB_EMAIL=$_GITHUB_EMAIL ./scripts/create_gh_pr
- name: 'gcr.io/$PROJECT_ID/github'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    echo "Create PR..."
    gh auth login --with-token < token.txt
    gh pr create -t "Publish a new NPM versions" -b "Updating NPM package version to $(cat version.bzl | grep DF_VERSION | awk '{ print $3 }' | sed "s/\"//g")" -B $BRANCH_NAME -H $(cat git_branch_name.txt)
options:
  automapSubstitutions: true
