steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      tail ~/.npmrc
    secretEnv: ['NPM_TOKEN']
  - name: gcr.io/cloud-builders/bazel:5.4.0
    entrypoint: bash
    args:
      - ./scripts/publish
availableSecrets:
  secretManager:
  - versionName: projects/178487900909/secrets/npm-publish-token/versions/1
    env: 'NPM_TOKEN'
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s
