config {
  type: "view",
  schema: "staging",
  description: "Cleaned version of stackoverflow.posts_answers",
  tags: ["staging"]
}

select
  id as post_id,
  creation_date as created_at,
  'answer' as type,
  title,
  body,
  owner_user_id,
  cast(parent_id as string) as parent_id
from
  ${ref("posts_answers")}
where
  -- limit to recent data for the purposes of this demo project
  creation_date >= timestamp("2019-01-01")
