config { type: "operation",
                      tags: ["tag1", "tag2"]
}

select CAST(REGEXP_EXTRACT("", r'^/([0-9]+)\'/.*') AS INT64) AS id,
       CAST(REGEXP_EXTRACT("", r"^/([0-9]+)\"/.*") AS INT64) AS id2,
       IFNULL (
         regexp_extract('', r'\a?query=([^&]+)&*'),
         regexp_extract('', r'\a?q=([^&]+)&*')
       ) AS id3,
       regexp_extract('bar', r'bar') as ID4 from ${ref("dab")}

where sample = 100