#!/bin/bash
set -e

./scripts/docs/build

mkdir -p /tmp/dataform/

# clone repo into new tmp dir

rm -rf /tmp/dataform/gh-pages

git clone -b gh-pages --single-branch git@github.com:tada-science/dataform.git /tmp/dataform/gh-pages

(cd /tmp/dataform/gh-pages && rm -rf *)

cp -R docs/out/* /tmp/dataform/gh-pages/

(cd /tmp/dataform/gh-pages && git add -A && git commit -a -m "docs publish script" && git push)
