WITH example_data AS (
SELECT user_timestamp AS user_timestamp, user_id AS user_id, user_action AS user_action
FROM 
  (SELECT 1502920304 AS user_timestamp,	03940	AS user_id, 'create_project' AS user_action) UNION ALL
  (SELECT 1502930293 AS user_timestamp,	20492	AS user_id, 'logout' AS user_action) UNION ALL
  (SELECT 1502940292 AS user_timestamp,	30920	AS user_id, 'login' AS user_action)
)

// This example uses a non default database; metadata retrieved should indicate to increment regardless.
config { type: "incremental", database: "TADA2" }

SELECT user_timestamp, user_id
FROM example_data

${ when(incremental(), `WHERE user_timestamp > (SELECT MIN(user_timestamp) FROM example_data)`) }
