config {
    type: "view",
    assertions: {
        uniqueKeys: ["val1", "val2"],
        nonNull: [
            "val2"
        ],
        rowConditions: [
            "val1 > 0",
            "val3 IS NULL AND val2 >= val1",
            "'fo''o' = 'fo''o'"
        ]
    }
}

select 1 as val1, 1 as val2, NULL as val3 union all
select 1 as val1, 2 as val2, NULL as val3 union all
select 1 as val1, 3 as val2, NULL as val3
