defaultProject: dataform-open-source
defaultLocation: us
defaultDataset: dataform_examples
defaultAssertionDataset: dataform_examples_assertions
defaultNotebookRuntimeOptions:
  outputBucket: gs://some-bucket
