defaultProject: dataform-open-source
defaultLocation: us
defaultDataset: dataform_extreme_weather_programming_example
defaultAssertionDataset: dataform_extreme_weather_programming_example_assertions
defaultNotebookRuntimeOptions:
  outputBucket: gs://some-bucket
  runtimeTemplateName: projects/test-project/locations/us-central1/notebookRuntimeTemplates/test-template
