#!/bin/bash
set -e

# Initialize build dir.

mkdir -p build

# Build protobufs.

mkdir -p build/protos

# Make sure scripts are executable.
chmod +x node_modules/protobufjs/cli/bin/pbjs
chmod +x node_modules/protobufjs/cli/bin/pbts

# Generate JS.
./node_modules/protobufjs/cli/bin/pbjs -t static-module -w commonjs \
  -p ./ \
  -o build/protos/index.js \
  protos/core.proto \
  protos/profiles.proto

# Generate TS.
./node_modules/protobufjs/cli/bin/pbts -o build/protos/index.d.ts build/protos/index.js

# Compile other TS.

npx tsc $@

# Copy over all package.json files.

cp --parents ./*/package.json build/

# Copy over data directories.

cp -R examples build/

# Copy over the development build package.json and install local deps.

cp package.json build/package.json

(cd build && npm i)

# Copy over the lerna.json file.

cp lerna.json build/
