#!/bin/bash

for warehouse in bigquery redshift snowflake sqldatawarehouse
do
  gcloud kms decrypt \
    --plaintext-file=test_credentials/${warehouse}.json \
    --ciphertext-file=test_credentials/${warehouse}.json.enc \
    --keyring=dataform-co-build --key=dataform-co-build --location=global
done
