#!/bin/bash

for file in \
  test_credentials/bigquery.json \
  test_credentials/redshift.json \
  test_credentials/snowflake.json \
  test_credentials/sqldatawarehouse.json \
  tools/stackdriver-github-bridge/env.yaml
do
  gcloud kms decrypt \
    --plaintext-file=${file} \
    --ciphertext-file=${file}.enc \
    --keyring=dataform-co-build --key=dataform-co-build --location=global
done
