#!/bin/bash

gcloud kms decrypt \
  --plaintext-file=test_credentials/bigquery.json \
  --ciphertext-file=test_credentials/bigquery.json.enc \
  --keyring=dataform-co-build --key=dataform-co-build --location=global

gcloud kms decrypt \
  --plaintext-file=test_credentials/redshift.json \
  --ciphertext-file=test_credentials/redshift.json.enc \
  --keyring=dataform-co-build --key=dataform-co-build --location=global


gcloud kms decrypt \
  --plaintext-file=test_credentials/snowflake.json \
  --ciphertext-file=test_credentials/snowflake.json.enc \
  --keyring=dataform-co-build --key=dataform-co-build --location=global