#!/bin/bash

gcloud kms decrypt \
    --ciphertext-file=$1.enc \
    --plaintext-file=$1 \
    --project=dataform-public \
    --keyring=dataform-builder-keyring \
    --key=dataform-builder-key \
    --location=global
