#!/bin/bash
set -e

# Clean and run tests before we publish.

./scripts/clean
./scripts/test

# Update to a new version.

npx lerna version

# Build the project with the new version.

./scripts/build

# Publish the new built packages.

(cd build && npx lerna publish from-package --no-git-tag-version $@)
