#!/bin/bash
set -e

bazel run @nodejs//:npm config set registry https://us-npm.pkg.dev/artifact-foundry-prod/npm-3p-trusted/
rm ./package-lock.json # Use repository versions instead
bazel run @nodejs//:npm install -- --legacy-peer-deps

# Run unit tests
./scripts/run_tests

# Run integration tests
./scripts/run_integration_tests
