#!/bin/bash
set -e

# Run eslint.
bazel build //:eslint && BAZEL_BINDIR=. ./bazel-bin/eslint_/eslint '**/*.ts'

# Run unit tests
bazel test ... \
  --test_tag_filters=-integration \
  --build_tests_only \
  "$@"
