#!/bin/bash
set -e

# Run eslint.
bazel run //:eslint -- '**/*.ts'

# Run integration tests
bazel test ... \
  --test_tag_filters=integration \
  --build_tests_only \
  --test_env=USE_CLOUD_BUILD_NETWORK=true
