#!/bin/bash
set -e

# Run tslint.
bazel run @nodejs//:yarn
bazel build @npm//tslint/bin:tslint && bazel-bin/external/npm/tslint/bin/tslint.sh --project .

# Run all the tests
bazel test ... \
  --test_tag_filters=-integration \
  --build_tests_only
