#!/bin/bash
set -e

bazel run @nodejs//:yarn

# Run eslint.
bazel build @npm//eslint/bin:eslint && bazel-bin/external/npm/eslint/bin/eslint.sh --rulesdir eslint-rules '**/*.ts'

# Run integration tests
bazel test ... \
  --test_tag_filters=integration \
  --build_tests_only \
  --test_env=USE_CLOUD_BUILD_NETWORK=true
