#!/bin/bash
set -e

bazel run @nodejs//:yarn config set registry https://us-npm.pkg.dev/artifact-foundry-prod/npm-3p-trusted/
rm ./yarn.lock
bazel run @nodejs//:yarn install
cat ./yarn.lock

# Run unit tests
./scripts/run_tests

# Run integration tests
./scripts/run_integration_tests
