#!/bin/bash
set -e

## Build tarballs that our test projects depend on.

bazel build \
  //core:package_tar \
  //crossdb:package_tar \
  //protos:package_tar

## We do this outside of bazel, just because it's a PITA.

(cd examples/bigquery && npm i)
(cd examples/bigquery_backwards_compatibility && npm i)
(cd examples/bigquery_with_errors && npm i)
(cd examples/redshift && npm i)
(cd examples/redshift_operations && npm i)
(cd examples/snowflake && npm i)

## Run tests.

bazel run //tests -- $@
