WITH example_data AS (
SELECT ts AS ts, id_1 AS id_1, id_2 AS id_2, val AS val
FROM 
  (SELECT 1 AS ts, 	21	AS id_1, 31 AS id_2, 'not_partitioned' AS val) UNION ALL
  (SELECT 2 AS ts,	22	AS id_1, 32 AS id_2, 'not_partitioned' AS val) UNION ALL
  (SELECT 3 AS ts,	21	AS id_1, 31 AS id_2, 'original' AS val) UNION ALL
  (SELECT 4 AS ts,	22	AS id_1, 32 AS id_2, 'original' AS val) UNION ALL
  (SELECT 5 AS ts,	21	AS id_1, 31 AS id_2, 'new' AS val) UNION ALL
  (SELECT 6 AS ts,	22	AS id_1, 32 AS id_2, 'new' AS val)
)

config {
  type: "incremental",
  uniqueKey: ["id_1", "id_2"],
  bigquery: {
    partitionBy: "RANGE_BUCKET(ts, GENERATE_ARRAY(0, 6, 2))",
    updatePartitionFilter: "ts > 2"
  },
  hermetic: false
}

SELECT ts, id_1, id_2, val
FROM example_data

${ when(incremental(), `WHERE ts > 2 AND ts <= 4`, `WHERE ts > 4 AND ts <= 6`) }
