config { 
    type: "view",
    description: "An example view",
    columns: {
        val: {
            description: "val doc",
            bigqueryPolicyTags: "projects/dataform-integration-tests/locations/eu/taxonomies/3546360117715097846/policyTags/6995291324014833226"
        }
    },
    bigquery: {
        labels: {
            label1: "val1",
            "label2": "val2"
        }
    }
}
select * from ${ref("sample_data")}
