WITH example_data AS (
SELECT user_timestamp AS user_timestamp, user_id AS user_id, user_action AS user_action, nested_data as nested_data
FROM 
  (SELECT 1502920304 AS user_timestamp,	03940	AS user_id, 'create_project' AS user_action, STRUCT(1 AS user_timestamp, 2 as user_id) as nested_data) UNION ALL
  (SELECT 1502930293 AS user_timestamp,	20492	AS user_id, 'logout' AS user_action, STRUCT(1 AS user_timestamp, 2 as user_id) as nested_data) UNION ALL
  (SELECT 1502940292 AS user_timestamp,	30920	AS user_id, 'login' AS user_action, STRUCT(1 AS user_timestamp, 2 as user_id) as nested_data)
)

config { 
    type: "incremental",
    description: "An incremental table",
    columns: {
        user_timestamp: "the timestamp",
        user_id: "the id",
        nested_data: {
          description: "some nested data with duplicate fields",
          columns: {
            user_timestamp: "nested timestamp",
            user_id: "nested id"
          }
        }
    }
}

SELECT user_timestamp, user_id, nested_data
FROM example_data

${ when(incremental(), `WHERE user_timestamp > (SELECT MIN(user_timestamp) FROM example_data)`) }
