load("//tools:ts_library.bzl", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_library(
    name = "compilation_sql",
    srcs = [
        "index.ts",
    ],
    deps = [
        "//protos:ts",
    ]
)
