name: Test

on: pull_request

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        # 7.3.2
        uses: gcr.io/cloud-builders/bazel@sha256:aa6c5ffd0d6d37960715d9c3392ba885e6484322c81c3604a90ccfb15c07c110
        entrypoint: bash
        with:
          args: ./scripts/run_tests

      - name: Run integration tests
        # 7.3.2
        uses: gcr.io/cloud-builders/bazel@sha256:aa6c5ffd0d6d37960715d9c3392ba885e6484322c81c3604a90ccfb15c07c110
        entrypoint: bash
        with:
          args: ./scripts/run_integration_tests
