name: Test

on: pull_request

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        uses: gcr.io/cloud-builders/bazel:5.4.0
        entrypoint: bash
        with:
          args: ./scripts/run_tests
