config { type: "incremental", protected: true }

js {  const crossdb = require("@dataform/crossdb"); }

select * from (
    select ${crossdb.currentTimestampUTC()} as ts
)

${when(incremental(), `where ts > (select max(ts) from ${self()}) or (select max(ts) from ${self()}) is null`)}

pre_operations {
    select ${when(incremental(), 1, 2)}
}

post_operations {
    select ${when(incremental(), 15, 16)}
}
