config { type: "incremental", protected: true, hermetic: false }

js {  const sql = require("@dataform/sql"); }

select * from (
    select ${sql().timestampCurrentUTC()} as ts
)

${when(incremental(), `where ts > (select max(ts) from ${self()}) or (select max(ts) from ${self()}) is null`)}

pre_operations {
    select ${when(incremental(), 1, 2)}
}

post_operations {
    select ${when(incremental(), 15, 16)}
}
