export function injectGlobalStyles() {
  require("df/components/blueprint/buttons.global.css");
  require("df/components/blueprint/callout.global.css");
  require("df/components/blueprint/card.global.css");
  require("df/components/blueprint/dialog.global.css");
  require("df/components/blueprint/drawer.global.css");
  require("df/components/blueprint/navbar.global.css");
  require("df/components/blueprint/popover.global.css");
  require("df/components/blueprint/toast.global.css");
  require("df/components/blueprint/tooltip.global.css");
  require("df/components/blueprint/core.global.css");
  require("df/components/blueprint/tag.global.css");
  require("df/components/blueprint/icons.global.css");
  require("df/components/blueprint/datetime.global.css");
  require("df/components/blueprint/table.global.css");
  require("df/components/blueprint/select.global.css");
  require("df/components/blueprint/custom.global.css");
  require("df/components/blueprint/colors.global.css");
}
